# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Navigate to storybook directory
        run: cd storybook
      - name: Install dependencies
        run: yarn
      - name: Build Project
        run: yarn build
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
